# Generated by Django 5.1 on 2024-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_favoritesharetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('genre_ids', models.JSONField()),
                ('genres', models.JSONField()),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_path', models.URLField()),
                ('backdrop_path', models.URLField()),
                ('vote_average', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='favoritesharetoken',
            name='token',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
